name: 'Unsplash Stats Workflow'
author: 'Gabriel Ramos (@gabrieluizramos)'
description: 'Adds Unsplash Stats to your Github Profile'

inputs:
  username:
    description: 'Unsplash username'
    required: true
  ACCESS_KEY: 
    description: 'Unsplash Access Key'
    required: true
  SECRET_KEY:
    description: 'Unsplash Secret Key'
    required: true

outputs:
  stats:
    description: 'stats'

runs:
  using: 'node12'
  main: 'action/index.js'
