on: [push]

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: A job to print Unsplash Stats
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm install

    - name: stats
      uses: ./
      with:
        file: './README.test.md'
        username: gabrieluizramos
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}